### ISSUE TITLE
Creating a new socket for every UDP send is inefficient

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#11]
In repy v2, a new UDP socket is created for each call to sendmessage. Based on the results of testing, this is significantly less efficient than reusing an existing UDP socket, and is more likely to result in a abnormally large delay. Graphs are attached comparing the existing implementation to python socket behavior for creating a new socket each time and for reusing the same socket each time.

It would be nice if sendmessage was moved to be a method of the UDP socket class.

**Comment by aaaaalbert** [comment]
This is fixed as a by-product of #9 I think. Closing!
