### ISSUE TITLE
Large UDP messages crash the sandbox

### ISSUE THREAD

**Issue by aaaaalbert** [SeattleTestbed/repy_v2#113]
As found out by @XuefengHuang and easily demonstrated through [this new unit test](https://github.com/aaaaalbert/repy_v2/blob/fix-UDP-quirks/testsV2/ut_repyv2api_udp_test_datagram_sizes.r2py), the `sendmessage` function crashes the RepyV2 sandbox if the user-supplied `message` is too large.

Exactly _how_ large a message must be to become problematic is platform-specific: On Mac OS X 10.11.3 with a stock Python 2.7.10 where I tested, `sysctl net.inet.udp.maxdgram` gives a maximum UDP datagram size of 9216, and exceeding it causes an uncatchable `Internal error` via `socket.error`:

```
albert$ python repy.py restrictions.default ut_repyv2api_udp_test_datagram_sizes.r2py 
Message length 1000 works. 
Message length 1600 works. 
Message length 9216 works. 
Message length 9217Internal Error

---
Uncaught exception!

---
Following is a full traceback, and a user traceback.
The user traceback excludes non-user modules. The most recent call is displayed last.

Full debugging traceback:
  "/private/tmp/rv2/RUNNABLE/namespace.py", line 1207, in wrapped_function
  "/private/tmp/rv2/RUNNABLE/emulcomm.py", line 889, in sendmessage

User traceback:

Exception (with class 'socket.error'): [Errno 40] Message too long

---
```

For comparison, on an Ubuntu 14.04 (32 bit) VM, we see the expected max (see the unit test why this value is expected):

```
$ python repy.py restrictions.default ut_repyv2api_udp_test_datagram_sizes.r2py 
Message length 1000 works. 
Message length 1600 works. 
Message length 9216 works. 
Message length 9217 works. 
Message length 10000 works. 
Message length 65507 works. 
Message length 65508Internal Error

---
Uncaught exception!

---
Following is a full traceback, and a user traceback.
The user traceback excludes non-user modules. The most recent call is displayed last.

Full debugging traceback:
  "/tmp/repy_v2/RUNNABLE/namespace.py", line 1207, in wrapped_function
  "/tmp/repy_v2/RUNNABLE/emulcomm.py", line 889, in sendmessage

User traceback:

Exception (with class 'socket.error'): [Errno 90] Message too long

---
Terminated
```

I would like to see results from Windows machines too, so if @priyam3nidhi and @kellender could please lend a hand.

---

Proposed fix: Check the message size in `emulcomm.py`, and raise a `RepyArgumentError` if the size exceeds Mac OS X's limit. (We could only change that limit on OS X through `sysctl -w`, and I don't think it's a good idea to do that.)

**Comment by kellender** [comment]
I looked at the unit test, and get the same error for my windows machine also.
And for convenience here it is on Appveyor: https://ci.appveyor.com/project/kellender/seattlelib-v2

..\GitHub\seattlelib_v2\RUNNABLE [Large-UDP-mdgs +2 ~0 -0 !]> python utf.py -f ut_repyv2api_udp_test_datagram_sizes.r2py
Testing module: repyv2api
        Running: ut_repyv2api_udp_test_datagram_sizes.r2py          [ FAIL ]
--------------------------------------------------------------------------------
Standard error :
..............................Produced..............................
Internal Error
---
Uncaught exception!
---
Following is a full traceback, and a user traceback.
The user traceback excludes non-user modules. The most recent call is displayed last.

Full debugging traceback:
  "C:\Users\Ajay S\Documents\GitHub\seattlelib_v2\RUNNABLE\namespace.py", line 1207, in wrapped_function
  "C:\Users\Ajay S\Documents\GitHub\seattlelib_v2\RUNNABLE\emulcomm.py", line 889, in sendmessage

User traceback:

Exception (with class 'socket.error'): [Errno 10040] A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself
---

..............................Expected..............................
None
--------------------------------------------------------------------------------

**Comment by aaaaalbert** [comment]
Thanks, and :+1: for doing this on AppVeyor!

Can you try and run the test outside of `utf.py`, please? Just the plain
```
python repy.py restrictions.default ut_repyv2api_udp_test_datagram_sizes.r2py 
```
so that we see what the size limit actually is.

**Comment by kellender** [comment]
sorry habit

```
C:\Users\Ajay S\Documents\GitHub\seattlelib_v2\RUNNABLE [Large-UDP-mdgs +2 ~0 -0 !]> python repy.py restrictions.default ut_repyv2api_udp_test_datagram_sizes.r2py
Message length 1000 works.
Message length 1600 works.
Message length 9216 works.
Message length 9217 works.
Message length 10000 works.
Message length 65507 works.
Message length 65508Internal Error
---
Uncaught exception!
---
Following is a full traceback, and a user traceback.
The user traceback excludes non-user modules. The most recent call is displayed last.

Full debugging traceback:
  "C:\Users\Ajay S\Documents\GitHub\seattlelib_v2\RUNNABLE\namespace.py", line 1207, in wrapped_function
  "C:\Users\Ajay S\Documents\GitHub\seattlelib_v2\RUNNABLE\emulcomm.py", line 889, in sendmessage

User traceback:

Exception (with class 'socket.error'): [Errno 10040] A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself
```

**Comment by aaaaalbert** [comment]
Checked on Mac OS X again: First, `sudo` is required to modify `net.inet.udp.maxdgram`. In other words, Seattle cannot (safely, sanely) do this.

Second, if I increase the value to 2**16-1 (or larger), the test outcomes are like what you see on Windows and Linux, i.e. the upper datagram length limit is 65507 bytes before the `socker.error` arises.

**Comment by awwad** [comment]
So there are two things we may care about here:

1. Consistency across platforms
2.  Preventing sandbox crash

**Comment by awwad** [comment]
@XuefengHuang and @vladimir-v-diaz will review this when they have time and let me know if anything seems lacking. (:
