### ISSUE TITLE
`SafeDict.update` needs `hasattr`

### ISSUE THREAD

**Issue by aaaaalbert** [SeattleTestbed/repy_v2#125]
Short and simple RepyV2 test:

``` python
a = SafeDict({"1":2})
a.update({"3":4})
log(a, "\n")
```

Problem:

```
(...)
  "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 188, in update

Unsafe call: ("Unsafe call 'hasattr' with args '({'3': 4}, 'iteritems')', kwargs '{}'",)
```

Fix:

``` diff
97a98
> UserDict.hasattr = hasattr
```

Other `dict` features likely need the same / a similar fix, and tests too!

**Comment by JustinCappos** [comment]
Are there any security concerns with this?  We blocked the *attr calls due
to the potential for introspection-based abuse...

**Comment by aaaaalbert** [comment]
We should be fine. The proposed patch would not expose `hasattr` to sandboxed code. It's identical to exising caches of `hasattr`/`getattr` and friends in `safe`, `emulcomm`, `namespace` etc.

The usual Repy safety precatautions still apply; the call would be cached for the last element in the call chain: (user code) --> (wrapped sandbox call) --> (lower-level implementation) --> (its imports and subimports)

**Comment by JustinCappos** [comment]
got it!
