### ISSUE TITLE
Change nmclient.repy for RepyV2 to comply with the RepyV2 network API

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#31]
nmclient.repy needs to be changed in the RepyV2 version in order to get it working with RepyV2 nodemanager. The current version of nmclient.repy only allows us to run RepyV1 code on vessels. Recently we added a new call in the nodemanager API (StartVesselEx) that allows us to run RepyV2 code as well as RepyV1 code on vessels. nmclient.repy needs to be modified so users are able to use it to upload and run RepyV2 code on vessels.

**Comment by aaaaalbert** [comment]
I don't think this is something that `nmclient` ever did. `nmAPI` is responsible for starting sandboxes, and already contains the code for RepyV2 vessels: https://github.com/SeattleTestbed/nodemanager/blob/master/nmAPI.py#L313-L414 . On the client side, `seash` has `seash_helper` that also does V2: https://github.com/SeattleTestbed/seash/blob/master/seash_helper.py#L551-L573
