### ISSUE TITLE
Update all the nm tests to comply with RepyV2 and use the updated nmclient.repy

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#32]
All the nodemanager tests need to be updated and use the new nmclient.repy. This will have to be done after #1133 has been resolved.

**Comment by aaaaalbert** [comment]
This is (1) a SeattleTestbed/nodemanager issue, and (2) long fixed there, see SeattleTestbed/nodemanager@895b5a6361b3e3900d5ce2666bef3e77622b62dc, SeattleTestbed/nodemanager@21dd4518f46e80a20e61c28c69d1eb37dd002c3b, SeattleTestbed/nodemanager@b1e72f5690732c4bce7abd0b27fd0dc9a5ea44d6, SeattleTestbed/nodemanager@20980e9f06ee38447846842956e1809c366da5ca, SeattleTestbed/nodemanager@a09af4f2500acba898690730e7135596444c204d, and perhaps others. Closing!
