### ISSUE TITLE
Empty textops.py in repy_v2/repy can supersede the real library

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#34]
The placeholder textops.py in repy_v2/repy/textops.py can supersede the textops.py library in repy_v2/seattlelib/textops.py when you copy them all to the same directory. This causes textops calls to break.

(I saw this after running preparetest.py, I'm not sure why this happened since it's supposed to copy seattlelib ''after'' repy)

**Comment by aaaaalbert** [comment]
The dir layout has changed, and the single `textops.py` we still have now comes from `seattlelib_v2`:  https://github.com/SeattleTestbed/seattlelib_v2/blob/master/textops.py
