### ISSUE TITLE
Thread.is_alive() is a new in Python 2.6 and should not be used since we support 2.5

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#39]
The call Thread.is_alive() is new in Python 2.6 it seems, and we should not use it. Instead we should be using either Thread.isAlive() or find an alternate solution. There are many reference to Thread.is_alive() in the RepyV2 branch in our repository, and these should be cleaned up.

**Comment by aaaaalbert** [comment]
The only mention of a function named `is_alive` is in `seattlelib_v2/librepythread.r2py` which is a user-space library that does not access the Python 2.7 function in any way, but just happens to define a function of that name. We use `Thread.isAlive` everywhere else in actual Python code. Closing!
