### ISSUE TITLE
[Newcomer] Deploy NAT Forwarders on 5-10 nodes.

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#40]
We need to deploy NAT forwarders on several nodes so nodes behind NAT can be accessed using the forwarders. The forwarders currently reside in seattle/branches/repy_v2/shims/nat_forwarder.

**Comment by aaaaalbert** [comment]
We currently run around 20 TCP relays on Planet-Lab and other machines. The current codebase is this: https://github.com/SeattleTestbed/affix/tree/master/services/tcp_relay
