### ISSUE TITLE
[Newcomer] Find ideal number of clients and servers that each NAT forwarder should have.

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#41]
Some experiments need to be run in order to figure out what the ideal number of servers and clients each NAT forwarder should handle. Currently it defaults to 5 servers and 5 clients per server.

**Comment by aaaaalbert** [comment]
The currently deployed TCP relay code tries to do this by assuming that the number of available threads is the limit.

https://github.com/SeattleTestbed/affix/tree/master/services/tcp_relay
