### ISSUE TITLE
[Newcomer] Balance load between NAT forwarders

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#43]
We need a method for balancing the load on the NAT forwarders. We don't want all the nodes behind a NAT to be using the same forwarder. Perhaps we can find a forwarder depending on the geographical location?

**Comment by aaaaalbert** [comment]
Also implemented using random sampling in the current TCPRelayAffix, https://github.com/SeattleTestbed/affix/blob/master/components/tcprelayaffix.r2py#L415-L418
