### ISSUE TITLE
[Newcomer] Librepysocket needs to be well tested.

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#45]
We need to test librepysocket thoroughly and ensure that all the functions work properly. We need to ensure that the semantics for the API calls match properly since many of the seattle library files have not been ported over to Repy V2 yet.

**Comment by aaaaalbert** [comment]
This is a SeattleTestbed/seattlelib_v2 issue, not a RepyV2 issue. Closing.
