### ISSUE TITLE
Porting Android-specific changes from RepyV1 to RepyV2

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#47]
In a little intercontinental debugging session, Lai Wang and I discovered a source of problems for RepyV2 on Android: RepyV2 was branched off before many of the Android fixes (r4853, r5634,  #1084 and fixes, r4905, r4881, ) were introduced.

r4853 is direly missing. Without it we can't even get ```repy.py``` (V2) print its usage options and not crash.

**Comment by aaaaalbert** [comment]
Referenced revisions I find integrated:
* https://seattle.poly.edu/changeset/4853/seattle
* https://seattle.poly.edu/changeset/5634
* https://seattle.poly.edu/changeset/4905
* https://seattle.poly.edu/changeset/4881
* https://seattle.poly.edu/changeset/5639

Other issues: https://seattle.poly.edu/changeset/5649 and https://seattle.poly.edu/changeset/5656 relate to utf.py.
