### ISSUE TITLE
[Newcomer] ut_repyv2api_openfileconsumesfilehandles.py fails on Linux

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#48]
These lines of the unit tests are giving us problems:
```
# Open random files
for x in xrange(MAX_FILES):
  filehandles[x] = openfile(files[x], False)
```

openfile does not allow uppercase letters in filenames. However, README.txt is the first file that is obtained.  For this below sample, I commented out the openfile call, and logged the filenames instead:

```
README.txt
testsemaphore_simple.py
loggingrepy.pyc
onehopdetourshim.repy
nanny.py
```

Perhaps all we need to do is to modify the unit test to skip any files with capitals.

**Comment by aaaaalbert** [comment]
Per discussion with @kellender: Having the assumed maximum number of file handles hardcoded isn't a good idea either.

**Comment by aaaaalbert** [comment]
Thanks @kellender for the PR!
