### ISSUE TITLE
Dylink should require an extension...

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#54]
The dylink calls shouldn't "helpfully" provide out an extension.   This has caused us confusion and masked bugs.

So you should need to say "uniqueid.repy" or "uniqueid.py" not "uniqueid" and it just picks whichever it prefers.

**Comment by aaaaalbert** [comment]
Fixed in SeattleTestbed@546707bca2c4827b28b96d398d8220a0e5ed1756.
