### ISSUE TITLE
Unit test ut_repyv2api_connectionserversendblocks.py fails on San's Linux box...

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#58]
Sam Burnett was running the unit tests on Repy V2 on his Arch Linux desktop machine and has the following error:

```
        Running: ut_repyv2api_connectionserversendblocks.py         [ FAIL ]
--------------------------------------------------------------------------------
Standard error :
..............................Produced..............................

---
Uncaught exception!

---
Following is a full traceback, and a user traceback.  
The user traceback excludes non-user modules. The most recent call is displayed last.

Full debugging traceback:
  "repy.py", line 154, in execute_namespace_until_completion
  "/tmp/tests/virtual_namespace.py", line 117, in evaluate
  "/tmp/tests/safe.py", line 586, in safe_run
  "ut_repyv2api_connectionserversendblocks.py", line 42, in <module>

User traceback:
  "ut_repyv2api_connectionserversendblocks.py", line 42, in <module>

Exception (with type 'exceptions.AssertionError'): 

---

..............................Expected..............................
None
--------------------------------------------------------------------------------
```

I've taken a quick look.   It looks like this may happen when the amount of data that is buffered is very high.   Sam will check if this is the case on his system.

**Comment by aaaaalbert** [comment]
The two `assert`ions in `ut_repyv2api_connectionserversendblocks.py` are peculiar.

[First](https://github.com/SeattleTestbed/repy_v2/blob/4db9ecd48a4577d646e4c38cf1af634dd8600810/testsV2/ut_repyv2api_connectionserversendblocks.py#L36) it is asserted that `socketobject.send` always send something, never zero bytes. This is not supported by the [current implementation in `emulcomm.py`](https://github.com/SensibilityTestbed/repy_v2/blob/ce94f3e33442d94b5eeccffd806067e731c5f0af/emulcomm.py#L1870-L1880). (The assumption generally makes sense though: Usually you'd `sleep` when encountering a `SocketWouldBlockError`, but not check separately for having sent 0 bytes. There doesn't seem to be an "automated" mapping to a would-block error from the underyling socket implementation either).

[Second](https://github.com/SeattleTestbed/repy_v2/blob/4db9ecd48a4577d646e4c38cf1af634dd8600810/testsV2/ut_repyv2api_connectionserversendblocks.py#L40) it checks that the send call buffers *not exactly as much* as the maximum assumed send size, while it should check that *at most as much* as that size was buffered. This therefore is an actual problem in the unit test.

From my test on a Ubuntu 15.04 VM, `ut_repyv2api_connectionsendwilleventuallyblock.py` and `ut_repyv2api_listenclosesend.py` share the same problems.

**Comment by aaaaalbert** [comment]
For comparison, Mac OS 10.11.5 with Python 2.7.12 on a MacBookPro5,3 shows no `AssertionError`s in the three tests.

**Comment by aaaaalbert** [comment]
Note also that Repy socket buffer limiting plays a role, see SeattleTestbed/repy_v2#88. Operating under unlimited (or rather *automatically sized*) buffers, the socket often fails to block on Linux.

**Comment by aaaaalbert** [comment]
And indeed, aaaaalbert/repy_v2@05faeea fixes the three tests for my Linux VM.
