### ISSUE TITLE
resourcemanipulation.py parses all resources as float

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#59]
[resourcemanipulation.py](code:/seattle/branches/repy_v2/repy/resourcemanipulation.py) is responsible for reading in and parsing restrictions files, and making the contents available to `nanny`. It will however treat all resource values as `floats`, see [here](source:/seattle/branches/repy_v2/repy/resourcemanipulation.py#L177). This makes sense for things like consumption rates (`cpu`, `net`, `loop`, `disk`, `random`), but it also converts port numbers, Bytes used on disk and in memory, and socket, file, and thread counts.

This weird behavior is visible e.g. through `getresources`:

``````
({'loopsend': 1000000.0, 'netrecv': 10000.0, 'random': 10000.0, 'insockets': 5.0, 'fileread': 10000.0, 'netsend': 10000.0, 'connport': set(['messport': set([34612.0](]),)), 'diskused': 100000000.0, 'filewrite': 10000.0, 'lograte': 30000.0, 'filesopened': 5.0, 'looprecv': 1000000.0, 'events': 10.0, 'memory': 20000000.0, 'outsockets': 5.0, 'cpu': 0.5}, {'diskused': 0L, 'fileread': 0.0, 'loopsend': 0.0, 'filesopened': 0, 'lograte': 0.0, 'netrecv': 0.0, 'random': 0.0, 'insockets': 0, 'filewrite': 0.0, 'looprecv': 0.0, 'events': 1, 'messport': set(['memory': 5365760L, 'netsend': 0.0, 'connport': set([](]),)), 'outsockets': 0, 'cpu': 0.007458812, 'threadcpu': 0.007168}, [not fixed, using ```getresources``` for things like determining which ports are currently available to a program become unnecessarily cluttered with casting to ```int``` of set items.
----
Proposed fix: On parsing, check the category for resource (per [source:seattle/branches/repy_v2/repy&resource_constants.py resourceconstants.py](])
``````

If)), and use the correct numeric type accordingly.

**Comment by aaaaalbert** [comment]
Closing this issue, it was fixed via ca83de7de7f2a71c97f692d7c4c14e5fe253b9d2 a while ago.
