### ISSUE TITLE
Run repy.py without restrictions?

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#61]
I believe there is no way to run `repy.py` without restrictions, except for providing a restrictions file with very high limits. (The `--simple` command-line option which by the way didn't make its way into RepyV2 yet doesn't do that.)

If this is supposed to be the One True Way of achieving practically unrestricted Repy, then we should distribute such restrictions file at least with the demokit.

An alternative could be to do what [repyportability.py](source:/seattle/branches/repy_v2/portability/repyportability.py) does and programmatically disable `nanny`'s checks.

Opinions?

**Comment by aaaaalbert** [comment]
Enough said. I'm closing the issue.
