### ISSUE TITLE
safe.py's safe_check() cannot access to builtins on second iteration

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#69]
```safe.py``` takes care of setting up an environment for executing Repy code that is free of potentially dangerous functions, and also Python builtins such as ```import```. However, it is so rigorous in doing that that its own function ```safe_check``` (and possibly others) loses access to the builtins once it has run.

Let's add some code to the top of ```safe_check```, e.g. due to #1080,
```
try:
  import android
  # Do Android-specific things for safety checking
except ImportError: 
  # Do something else
```

In the first iteration, the added code inside ```safe_check``` runs fine, and the Repy program gets checked without complaints. If the Repy program instantiates a virtual namespace though, that namespace will go through another round of ```safe_check```. This time around, the builtins are not available anymore, and trying to access them causes

```
Exception (with type 'exceptions.ValueError'): Code failed safety check! Error: ('__import__',)
```

(The fix for the example above is obvious, just ```try: import android``` once at the beginning of ```safe.py``` and communicate the result using a variable.)

----

I don't know if we should try fixing this behavior at all. The preconditions for problems are pretty strict I think (Repy program creating own virtual namespaces, and unconditionally required access to a builtin in ```safe_check```), and we are really erring on the safe (read: more restrictive) side right now. I didn't expect this behavior though, so at least it should be documented.

Source file reference:
source:/seattle/trunk/repy/safe.py@6424#L285 and source:/seattle/branches/repy_v2/repy/safe.py@6453#L274

**Comment by aaaaalbert** [comment]
I'll close this issue. The `SyntaxWarning` problem is dealt with in #114 now; for the problem of re-enabling certain builtins, it's probably safer to manually allow specific calls for specific libraries and/or do the `import`s upfront than to re-enable all builtins unconditionally once the sandboxed code runs.
