### ISSUE TITLE
Adding calls to the Repy API requires changes to dylink too

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#70]
In the Sensibility Testbed project, we added a function call to the Repy API. This made the call available to the main program. It would however not work in libraries included via ```dylink```. Once we also augment ```dylink```'s idea of the stock API ([this set](https://github.com/SeattleTestbed/seattlelib_v2/blob/master/dylink.r2py#L51-L56)) to include the new function call, it becomes available to libraries too.

From what I understand, ```namespace.py``` (see [code](source:seattle/branches/repy_v2/repy/namespace.py)) should define the Repy API (but see #71). We should probably try to reuse the definition in ```namespace``` rather than recreating (and having to keep in sync manually) the API in code.

**Comment by aaaaalbert** [comment]
Once #71 is fixed, we can change `dylink` to just introspect its `_context` and recreate `STOCK_API` from all the objects of `type 'instancemethod'`.

The reason for this seemingly weird type is that the Repy API functions are not visible as Python `function` types, but bound methods `NamespaceAPIFunctionWrapper.wrapped_function`. A template method for comparison may be created like so:

```python
class A():
  def b():
    pass

a = A()
type(a.b)   # <type 'instancemethod'>
```

**Comment by aaaaalbert** [comment]
This is really a SeattleLib issue. Superseded by SeattleTestbed/seattlelib_v2#184, closing.
