### ISSUE TITLE
Tautologous Repy API definitions in repy.py

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#71]
At the time of writing (r6962), ```repy.py``` ([code here](source:seattle/branches/repy_v2/repy/repy.py)) calls ```namespace.wrap_and_insert_api_functions``` ([code here](source:seattle/branches/repy_v2/repy/namespace.py#L136)) with a nearly empty user context in order to let ```namespace``` set up the Repy API the user will use. ```repy.py``` however overwrites two definitions, ```getresources``` and ```createvirtualnamespace```, and also adds  a completely new one, ```getlasterror```.

In the comments in ```repy.py```, we have two places labelled "BAD" that seem to talk about removing those overwrites/adds as well as an import. In RepyV1, we only call ```namespace``` and don't overwrite/add things. My feeling is that we should remove the "BAD" stuff, and add ```getlasterror``` to ```namespace```, but I'd like to have a second opinion on that.

**Comment by aaaaalbert** [comment]
FWIW, this issue will be fixed by some additional fixes to namespace wrapping that I'm developing over here, https://github.com/aaaaalbert/repy_v2/tree/fix-namespace-wrapping

**Comment by aaaaalbert** [comment]
Note: The branch mentioned above became PR #127 which was subsequently merged.
